<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/

$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/admin/admin.categories.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/dynatree/jquery.dynatree.min.js');
?>
<link type="text/css" href="<?php echo $this->webroot?>/privateModules/journal/public/js/lib/dynatree/skin/ui.dynatree.css" rel="stylesheet" />
<link type="text/css" href="<?php echo $this->webroot?>/privateModules/journal/public/css/admin/admin.categories.css" rel="stylesheet" />

<div class="viewMain">
  <h3>Manage Categories</h3>

  <div id="treeWrapper"></div>
  
  <br/><br/>
  <b>Add a new Tree:</b>
  <form action="" method="POST">
    <input type="text" name="newtree"/>
    <input type="submit" value="Save"/>    
  </form>  
  
  <script type="text/template" id="AddCategoryTemplate">
    <div style="display:none;" class="AddCategory">
      <b><a href="#" class="deleteCategory">Delete selected(<span class="ParentName"></span>) Category</a></b><br/>
      <b>Add a Child Category:</b>
      <form action="" method="POST">
        <input type="text" name="newCategory"/>
        <input type="hidden" class="parentCategory" name="parentCategory" value=""/>
        <input type="submit" value="Save"/>    
      </form>  
    </div>
    <div style="display:none;" class="AddRootCategory">
      <b>Add a root Category:</b>
      <form action="" method="POST">
        <input type="text" name="newCategory"/>
        <input type="hidden" name="parentCategory" value="{parent}"/>
        <input type="submit" value="Save"/>    
      </form>  
    </div>
    
  </script>
</div>

