<?php
/* =========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * ========================================================================= */
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/admin/admin.editor.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.tablesorter.css" />

<div class="viewMain">
  <h3>Manage Editors (<?php echo $this->name?>)</h3>

  <table id='memberListTable' class="tablesorter">
    <thead>
      <tr>
        <th width="80%">Member</th><th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <?php
      $stripeIndex = 0;
      foreach ($this->group->getUsers() as $user)
        {
        $stripeIndex++;
        $class = $stripeIndex % 2 ? 'odd' : 'even';
        echo '<tr class=' . $class . '>';
        echo '  <td width="80%">' . $this->linkuser($user) . '</td>';
        echo '  <td><span class="actionsList">';
        echo '  <a qtip="Remove editor" ' .
        '     class="tableActions removeMember" userId="' . $user->getKey() . '">';
        echo '    <img class="tableActions" alt="" src="' . $this->coreWebroot . '/public/images/icons/close.png" /></a>';
        echo '  </span></td>';
        echo '</tr>';
        }
      ?>
    </tbody>
  </table>
  
  <h4>Add new editor</h4>
  <div class='invitationSearch'>
    <input style="width:250px" type='text' id='live_invitation_search' value='Start typing a name ...' autocomplete='off' autocorrect='off' autocapitalize='off' />
    <input type='hidden' id='live_invitation_search_value' value='init' />
    <div id='searchInvitationLoading' style='display:none'></div>
  </div>


</div>

