<?php
/* =========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * ========================================================================= */
?>
<div >   
  <br/>
  <div align="center">
    <font size="+1"><strong>Disclaimer</strong>
    </font>
  </div>
  <br/>   
  <p>
  <form method="post" action="">
    <label>Name:</label>
    <input type="text" name="name" style="width:600px;" value="<?php echo $this->disclaimer->getName()?>"/>
    <br/>
    <br/>
    <label>Full description:</label>
    <textarea name="description" style="width:600px;height:150px;"><?php echo $this->disclaimer->getDescription()?></textarea>
    <br/>
    <br/>
    <input type="submit" value="Save >"/>
    <?php
    if($this->disclaimer->saved)
      {?>
      <input type="submit" name="delete" onclick="return confirm('Do you want to delete the disclaimer?');" value="Delete"/>
      <?php
      }?>
  </form>
  </p>


</div>
