<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/

$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/admin/admin.editissue.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/iCheck-master/jquery.icheck.min.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/parsley.min.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/pickadate.js-3.0.4/picker.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/pickadate.js-3.0.4/picker.date.js');
?>
<link type="text/css" href="<?php echo $this->webroot?>/privateModules/journal/public/css/admin/admin.editissue.css" rel="stylesheet" />
<link type="text/css" href="<?php echo $this->webroot?>/privateModules/journal/public/js/lib/iCheck-master/skins/minimal/minimal.css" rel="stylesheet" />
<link type="text/css" href="<?php echo $this->webroot?>/privateModules/journal/public/js/lib/pickadate.js-3.0.4/themes/default.css" rel="stylesheet" />
<link type="text/css" href="<?php echo $this->webroot?>/privateModules/journal/public/js/lib/pickadate.js-3.0.4/themes/default.date.css" rel="stylesheet" />

<div >   
  <br/>
  <div align="center">
    <font size="+1"><strong>Edit Journal</strong>
    </font>
  </div>
  <br/>   

  <form class="mainForm" action="" method="POST" data-validate="parsley">
  <table width="100%"  border="0">    
    <tr>      
      <td width="25%" style="vertical-align: top;">
        <div align="right"><strong>Name:</strong>
        </div></td>      
      <td width="75%">
        <input name="name" type="text" data-required="true" value="<?php echo $this->issue->getName()?>" />
    </tr>    
    <tr>      
      <td valign="top">
        <div align="right"><strong>Description:</strong>
        </div></td>      <td>
          <textarea name="short_description" ><?php echo $this->issue->getShortDescription()?></textarea>
      </td>    
    </tr>    
    
    <tr>         
    </tr>    
    <tr>      
      <td valign="top">
        <div align="right"><strong>Related Links:</strong>
        </div></td>      <td>
          <textarea name="related_link" ><?php echo $this->issue->getRelatedLink()?></textarea>
      </td>    
    </tr>
    
      <tr>      
      <td valign="top">
        <div align="right"><strong>License (Publisher):</strong>
        </div></td>      <td>
        Set license to
        <select onchange="ChangeAuthorLicense(this.value)" name="licensemenu">
        <option>Choose...</option>
        <?php
          function dirList ($directory)
             {
             $results = array();
             $handler = opendir($directory);
             while ($file = readdir($handler))
               {
               echo $file;
               if ($file != '.' && $file != '..' && $file != '.cvs' && $file != '.svn' && !is_dir($directory."/".$file))
                 {
                 $results[] = $file;
                 }
               }
              closedir($handler);
              return $results;
              }

            $licenses = dirList(BASE_PATH."/privateModules/journal/licenses");
            foreach($licenses as $license)
                {
                $text = file_get_contents(BASE_PATH."/privateModules/journal/licenses/".$license);
                echo "<option value=\"".htmlentities($text)."\"";
                echo ">".str_replace(".txt","",$license)."</option>";
                }
                ?> 
          </select> 
         <br/> or modify the following text:<br/>
         <textarea name="authorLicense" id="authorLicense"><?php echo $this->issue->getAuthorLicense()?></textarea>
       </td>
    </tr>
    
     <tr>      
      <td valign="top">
        <div align="right"><strong>License (Author):</strong>
        </div></td>      <td>
        Set license to
        <select onchange="ChangeReaderLicense(this.value)" name="copyrightmenu">
        <option>Choose...</option>
        <?php
            $licenses = dirList(BASE_PATH."/privateModules/journal/licenses/copyrights");
            foreach($licenses as $license)
                {
                $text = file_get_contents(BASE_PATH."/privateModules/journal/licenses/copyrights/".$license);
                echo "<option value=\"".htmlentities($text)."\"";
                echo ">".str_replace(".txt","",$license)."</option>";
                }
                ?> 
          </select> 
          <br/>or modify the following text:<br/>
          <textarea name="readerLicense" id="readerLicense"><?php echo $this->issue->getReaderLicense()?></textarea>
     </td>
    </tr>
    
    <tr>      
      <td valign="top">
        <div align="right"><strong>Paperdue date:</strong>
        </div></td>      <td>
          <input placeholder="Select a date." value="<?php echo str_replace(" 00:00:00", "",$this->issue->getPaperdueDate())?>" class="datepicker"  name="paperdue_date" data-required="true" data-type="dateIso"/>
       </td>    
    </tr>        
    <tr>      
      <td valign="top">
        <div align="right"><strong>Decision date:</strong>
        </div></td>      <td>
          <input placeholder="Select a date." value="<?php echo str_replace(" 00:00:00", "", $this->issue->getDecisionDate())?>"  class="datepicker" name="decision_date" data-required="true" data-type="dateIso"/>
        </td>    
    </tr>        
    <tr>      
      <td valign="top">
        <div align="right"><strong>Publication date:</strong>
        </div></td>      <td>
            <input placeholder="Select a date." value="<?php echo str_replace(" 00:00:00", "", $this->issue->getPublicationDate())?>"  class="datepicker" name="publication_date" data-required="true" data-type="dateIso"/>
        </td>    
    </tr>    
    <tr>      
      <td valign="top">
        <div align="right"><strong>Private:</strong>
        </div></td>      <td>
            <input type="checkbox" name="defaultpolicy" value="1" <?php echo $this->issue->getDefaultPolicy() == 1? "checked":""?>/>
       </td>    
    </tr>
    
    <!-- 
       0 means code and data
       1 means code only
       2 means data only
       3 means none -->        <td>&nbsp;</td>      <td>
      <input type="submit" name="data[Admin][cancel]" value="<< Cancel" />  
      <input type="submit" name="data[Admin][add]" value="Update Journal >>" /></td>    
    </tr>  
  </table>  
  </form>
</div>
