<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/

$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/parsley.min.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/admin/admin.help.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib//tinymce/tinymce.min.js');
?>
<div >   
  <br/>
  <div align="center">
    <font size="+1"><strong>Edit Help</strong>
    </font>
  </div>
  <br/>   

  <form class="mainForm" action="" method="POST" data-validate="parsley">
  <table width="100%"  border="0">    
 
    <tr>      
      <td valign="top">
        <div align="right"><strong>Main Help Page:</strong>
        </div></td>      <td>
          <textarea style="height:400px;"  data-required="true" name="helpcontent" ><?php echo $this->helpcontent?></textarea>
      </td>    
    </tr>    
    <tr>      
      <td valign="top">
        <div align="right"><strong>FAQ page:</strong>
        </div></td>      <td>
        <textarea style="height:400px;" data-required="true" name="faqcontent" ><?php echo $this->faqcontent?></textarea>
      </td>    
    </tr>    
    <tr>      
      <td valign="top">
        <div align="right"><strong>About page:</strong>
        </div></td>      <td>
        <textarea style="height:400px;" data-required="true" name="aboutcontent" ><?php echo $this->aboutcontent?></textarea>
      </td>    
    </tr>    
    <tr>         
    <tr>
    
    <td>&nbsp;</td>      <td>
      <input type="submit" value="Save >>" /></td>    
    </tr>  
  </table>  
  </form>
</div>
