<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/

$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/admin/admin.issues.js');
?>

<div >
  <br/>
  <div align="center">
    <font size="+1"><strong>Manage Journals and Issues</strong>
    </font>
  </div>
  <br/>

  <?php
  if($this->isAdmin)
    {
    echo '<a class="createCommunity">Create Journal</a>';
    }
    ?>

  <h4>Journals (also called communities):</h4>
  <ul>
    <?php
    foreach($this->communities as $community)
      {
      $isEditor = $this->isAdmin
              || !MidasLoader::loadModel('Group')->userInGroup($this->userDao, $community->getAdminGroup());

      $adminGroup = $community->getAdminGroup();
      if(!$adminGroup) continue;

      echo "<li style='margin-bottom:10px;'>".$community->getName();
      if($this->isAdmin)
        {
        echo " <a href='".$this->webroot."/journal/admin/groupusers?groupId=".$adminGroup->getKey()."&showmembers=1&name=".  urldecode("Journal: ".$community->getName())."'>Journal Editors and Members</a>, ";
        echo " <a href='".$this->webroot."/community/manage?communityId=".$community->getKey()."'>Manage Journal (Midas view)</a>, ";
        }
      if($isEditor)
        {
        echo "<a href='".$this->webroot."/journal/admin/editissue?communityId=".$community->getKey()."'>Create Issue</a>";
        }
      $folders = $community->getFolder()->getFolders();
      echo "<ul>";
      foreach($folders as $folder)
        {
        if($folder->getName() != "Public" && $folder->getName() !="Private")
          {
          $group = false;
          foreach($folder->getFolderpolicygroup() as $policy)
            {
            if($policy->getPolicy() == MIDAS_POLICY_ADMIN && $adminGroup->getKey() != $policy->getGroupId())
              {
              $group = $policy->getGroup();
              break;
              }
            }
          echo "<li>Issue: ".$folder->getName();
          if($isEditor && $group) echo " <a href='".$this->webroot."/journal/admin/groupusers?groupId=".$group->getKey()."&name=".  urldecode("Issue: ".$folder->getName())."'>Issue Editors</a>, ";
          if($isEditor) echo " <a href='".$this->webroot."/journal/admin/editissue?folderId=".$folder->getKey()."'>Edit</a>";
          echo "</li>";
          }
        }
      echo "</ul>";
      echo "</li>";
      }
      ?>
  </ul>
</div>
