<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/

$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/admin/admin.issues.js');
?>

<div >   
  <br/>
  <div align="center">
    <font size="+1"><strong>Manage Journals and Issues</strong>
    </font>
  </div>
  <br/>   
  <a class="createCommunity">Create Journal</a>
  
  <h4>Journals (also called communities):</h4>
  <ul>
    <?php
    foreach($this->communities as $community)
      {
      echo "<li style='margin-bottom:10px;'>".$community->getName()." <a href='".$this->webroot."/community/manage/?communityId=".$community->getKey()."'>Manage</a>, 
        <a href='".$this->webroot."/journal/admin/editissue?communityId=".$community->getKey()."'>Create Issue</a>";
      $folders = $community->getFolder()->getFolders();
      echo "<ul>";
      foreach($folders as $folder)
        {
        if($folder->getName() != "Public" && $folder->getName() !="Private")
          {
          echo "<li>Issue: <a href='".$this->webroot."/journal/admin/editissue?folderId=".$folder->getKey()."'>".$folder->getName()."</a></li>";
          }
        }
      echo "</ul>";
      echo "</li>";
      }
      ?>
  </ul>
</div>
