<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->webroot."/privateModules/journal/public/js/config/config.index.js");
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<div class="viewMain">
     <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/admin#tabs-modules'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');
            echo "</a>";
          echo '</div>';

        ?>
    </div>

     <?php
      echo "
      <form class='genericForm' id='configForm' method='POST'  action=''>
      <h3>Journal Configuration:</h3>
            <div>
              <label for='test'>Super Admin Email</label>
              <input type='text' name='adminEmail' value='".$this->adminEmail."'/>
            </div>
            <div>
              <label for='test'>Default Journal</label>
              <input type='number' name='defaultJournal' value='".$this->defaultJournal."'/>
            </div>
            <div>
              <label for='test'>Default Layout</label>
              <input type='text' name='defaultLayout' value='".$this->defaultLayout."'/>
            </div>
            <div>
              <label for='test'>Base Handle</label>
              <input type='text' name='baseHandle' value='".$this->baseHandle."'/>
            </div>
            <div>
              <label for='test'>Old Website URL</label>
              <input type='text' name='oldWebsiteUrl' value='".$this->oldWebsiteUrl."'/>
            </div>
            <div>
              <label for='test'>Index of licensing disclaimer</label>
              <input type='number' name='licenseDisclaimer' value='".$this->licenseDisclaimer."'/>
            </div>
            <br/>
            <div>
              <label for='test'>PostgreSQL Database Name</label>
              <input type='text' name='pgsqlDB' value='".$this->pgsqlDB."'/>
            </div>
            <div>
              <label for='test'>PostgreSQL password('postgres' user)</label>
              <input type='text' name='pgsqlPW' value='".$this->pgsqlPW."'/>
            </div>
            <div>
              <label for='test'>PostgreSQL port on the local machine</label>
              <input type='text' name='pgsqlPort' value='".$this->pgsqlPort."'/>
            </div>
          <div>
            <input type='submit' value='Save Configuration'/>
          </div>
       </form>";
       ?>

  <a href="<?php echo $this->webroot?>/journal/config/migrate">Migrate</a>
</div>
