<?php
/* =========================================================================
  MIDAS Server
  Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
  69328 Lyon, FRANCE.

  See Copyright.txt for details.
  This software is distributed WITHOUT ANY WARRANTY; without even
  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
  PURPOSE.  See the above copyright notices for more information.
  ========================================================================= */

$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/config/config.migrate.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');

$this->headLink()->appendStylesheet($this->coreWebroot . '/public/css/jquery/jquery.filetree.css');
$this->headLink()->appendStylesheet($this->webroot . '/privateModules/journal/public/css/config/config.migrate.css');
$this->headLink()->appendStylesheet($this->coreWebroot . '/public/css/assetstore/assetstore.add.css');
?>

<h2> Migrating Journal</h2>
<form id="migrateForm" enctype="application/x-www-form-urlencoded" action="" method="post" class="migrateForm">
  <dl class="zend_form">
    <dt id="midas2_hostname-label"><label for="midas2_hostname" class="required">MIDAS2 Hostname</label></dt>
    <dd id="midas2_hostname-element">
      <input type="text" name="midas2_hostname" id="midas2_hostname" value="localhost" size="60"></dd>
    <dt id="midas2_port-label"><label for="midas2_port" class="required">MIDAS2 Port</label></dt>
    <dd id="midas2_port-element">
      <input type="text" name="midas2_port" id="midas2_port" value="5432" size="4"></dd>
    <dt id="midas2_user-label"><label for="midas2_user" class="required">MIDAS2 User</label></dt>
    <dd id="midas2_user-element">
      <input type="text" name="midas2_user" id="midas2_user" value="midas" size="60"></dd>
    <dt id="midas2_password-label"><label for="midas2_password" class="required">MIDAS2 Password</label></dt>
    <dd id="midas2_password-element">
      <input type="password" name="midas2_password" id="midas2_password" value="" size="60"></dd>
    <dt id="midas2_database-label"><label for="midas2_database" class="required">MIDAS2 Database</label></dt>
    <dd id="midas2_database-element">
      <input type="text" name="midas2_database" id="midas2_database" value="midas" size="60"></dd>
    <dt id="midas2_assetstore-label"><label for="midas2_assetstore" class="required">MIDAS2 Assetstore Path</label></dt>
    <dd id="midas2_assetstore-element">
      <input type="text" name="midas2_assetstore" id="midas2_assetstore" value="C:/xampp/midas/assetstore" size="60"></dd>
    <div id="midas2_assetstore_button-label"><label for="midas2_assetstore_button" style="display:none" class="optional">Choose</label></div>
    <div class="browse-button">
      <button name="midas2_assetstore_button" id="midas2_assetstore_button" type="button">Choose</button></div>
    <dt id="assetstore-label"><label for="assetstore" class="required">MIDAS3 Assetstore</label></dt>
    <dd>
      <select name="assetstore" id="assetstore">
        <option value="0" label="Choose one...">Choose one...</option>
        <option value="1" label="Local">Local</option>
      </select>
      <a class="load-newassetstore" href="#newassetstore-form" rel="#newassetstore-form" title="Add a new assetstore"> Add a new assetstore</a></dd>
    <dt id="migratesubmit-label">&nbsp;</dt><dd id="migratesubmit-element">
      <button name="migratesubmit" id="migratesubmit" type="button">Migrate</button></dd></dl></form>

<?php
$this->setScriptPath(BASE_PATH . "/core/views");
echo $this->element('serversidefilechooser', 'default', array('id' => 'midas2_assetstore_button',
    'fileFilterErrorMsg' => 'Select the MIDAS2 assetstore directory on the server',
    'destSelector' => '#midas2_assetstore',
))
?>


<div id="newassetstore-form" style="display:none">
  <form id="assetstoreForm" enctype="application/x-www-form-urlencoded" action="<?php echo $this->webroot ?>/assetstore/add" method="post" class="assetstoreForm"><dl class="zend_form">
      <dt id="assetstorename-label"><label for="assetstorename" class="required">Give a name</label></dt>
      <dd id="assetstorename-element">
        <input type="text" name="name" id="assetstorename" value=""></dd>
      <dt id="assetstoreinputdirectory-label"><label for="assetstoreinputdirectory" class="required">Pick a base directory</label></dt>
      <dd id="assetstoreinputdirectory-element">
        <input type="text" name="basedirectory" id="assetstoreinputdirectory" value=""></dd>
      <dt id="assetstoretype-label"><label for="assetstoretype" class="optional">Select a type</label></dt>
      <dd>
        <select name="assetstoretype" id="assetstoretype">
          <option value="0" label="Managed by MIDAS">Managed by MIDAS</option>
          <option value="1" label="Remotely linked">Remotely linked</option>
        </select>
        <div class="assetstoreLoading" style="display:none"><img src="/Midas/Midas3/core/public/images/icons/loading.gif"></div></dd>
      <dt id="addassetstore-label">&nbsp;</dt><dd id="addassetstore-element">
        <input type="submit" name="addassetstore" id="addassetstore" value="Add this assetstore"></dd></dl></form>
</div>

<script language="javascript">
  var assetstores = eval(<?php echo json_encode($this->assetstores) ?>);
</script>
