<?php
/* =========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/processing/processing.index.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/fancyapp/source/jquery.fancybox.pack.js');
?>

<div class="viewMain">
  <div>
    <h3>View OTJ Survey Results</h3>
    <br />
    <pre>
      <?php
        $result = glob(BASE_PATH."/privateModules/journal/OTJ_Survey/".$_GET['id']."_Results.txt");
        if(count($result)==0)
          {
          echo "Results not found";
          }
        else
          {
          foreach($result as $file)
            {
            $surveyResults = fopen($file,'r');
            echo fread($surveyResults,filesize($file));
            fclose($surveyResults);
            };
          }
      ?>
    </pre>
  </div>
</div>
