
<div>
  <div align="center">
    <table bgcolor="#ffffff" border="0" width="100%" cellspacing="0" cellpadding="0">
      <tbody>
        <tr>
          <td style="padding:14px 14px 14px 14px" valign="top" rowspan="1" colspan="1" align="center">

            <table style="width:640px" border="0" width="1" cellspacing="0" cellpadding="0">
              <tbody>
                <tr>
                  <td style="background-color:#dfdfdf;padding:1px 1px 1px 1px" bgcolor="#dfdfdf" valign="top" rowspan="1" colspan="1" align="center">

                    <table style="background-color:#ffffff" bgcolor="#ffffff" border="0" width="100%" cellspacing="0" cellpadding="0">
                      <tbody>
                        <tr>
                          <td valign="top" rowspan="1" colspan="1" align="center">

                            <table border="0" width="100%" cellspacing="0" cellpadding="0">
                              <tbody>
                                <tr>

                                  <td style="padding:0px 0px 0px 0px" valign="top" width="100%" rowspan="1" colspan="1" align="center">

                                    <table style="background-color:#ffffff" bgcolor="#FFFFFF" border="0" width="100%" cellspacing="0" cellpadding="0">
                                      <tbody>
                                        <tr>
                                          <td style="color:#76b5be;font-family:Arial,Helvetica,sans-serif;font-size:10pt;padding:32px 32px 32px 32px" valign="center" rowspan="1" colspan="1" align="left">

                                            <div>
                                              <table>
                                                <tr>
                                                  <td>
                                                    <a shape="rect" href="http://www.osehra.org" target="_blank">
                                                      <img   vspace="0" border="0"  src="<?php echo $this->webroot; ?>/privateModules/journal/public/images/osehra/logo.jpg" />
                                                    </a>
                                                  </td>
                                                  <td>
                                                    <div style="width:150px;color: #999999;font-size: 14px;position: relative;font-weight: bold;top: 32px;">
                                                      OSEHRA Technical Journal
                                                    </div>
                                                  </td>
                                                </tr>
                                              </table>


                                            </div>

                                          </td>
                                          <td style="color:#76b5be;font-family:Arial,Helvetica,sans-serif;font-size:10pt;padding:32px 32px 32px 0px" valign="center" width="100%" rowspan="1" colspan="1" align="right">
                                            <div>
                                              <b>
                                                <i><?php echo date('F j, Y')?></i>
                                              </b>
                                            </div>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>

                                    <table style="margin:0px 0px 0px 0px" border="0" width="100%" cellspacing="0" cellpadding="0">
                                      <tbody>
                                        <tr>
                                          <td style="padding:0px 0px 0px 0px;height:1px;line-height:1px" rowspan="1" colspan="1">
                                            <table border="0" width="100%" cellspacing="0" cellpadding="0">
                                              <tbody>
                                                <tr>
                                                  <td style="padding-bottom:9px;background-color:#76b5be;height:1px;line-height:1px" height="1" bgcolor="#76b5be" rowspan="1" colspan="1" align="center">
                                                                                               </td>

                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>

                                  </td>

                                </tr>
                              </tbody>
                            </table>
                            
                            <?php echo $this->content?>
       
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
              </tbody>
            </table>

          </td>
        </tr>
      </tbody>
    </table>

  </div>
  
</div>
