

<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>

      <td style="padding:0px 0px 0px 0px" valign="top" width="100%" rowspan="1" colspan="1" align="center">

        <table border="0" width="100%" cellspacing="0" cellpadding="0">
          <tbody>
            <tr>
              <td style="color:#454545;font-family:Arial,Helvetica,sans-serif;font-size:10pt;padding:8px 32px 9px 32px" valign="top" rowspan="1" colspan="1" align="left">

                <div>
                  <br>
                  <p style="text-align:justify;text-justify:inter-word;">Hello,</p>
                  <br>
                  <p style="text-align:justify;text-justify:inter-word;">A new submission needs your approval. </p>
                  <br>
                  <p style="text-align:justify;text-justify:inter-word;">Title: <?php echo $this->name ?>. </p>
                  <br>
                  <p style="text-align:justify;text-justify:inter-word;">Authors: <?php echo $this->author ?>. </p>
                  <br>
                  <p style="text-align:justify;text-justify:inter-word;">Abstract: </p>
                  <br>
                  <p style="text-align:justify;text-justify:inter-word;"><?php echo $this->description ?></p>
                  <br>
                  <p style="text-align:justify;text-justify:inter-word;">To approve this submission please login in and go to <a href="<?php echo ($this->webroot . $this->link) ?>" target="_blank">here</a></p>
                <br/>
              </td>
            </tr>
          </tbody>
        </table>


      </td>

    </tr>
  </tbody>
</table>
