

<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tbody>
    <tr>

      <td style="padding:0px 0px 0px 0px" valign="top" width="100%" rowspan="1" colspan="1" align="center">

        <table border="0" width="100%" cellspacing="0" cellpadding="0">
          <tbody>
            <tr>
              <td style="color:#454545;font-family:Arial,Helvetica,sans-serif;font-size:10pt;padding:8px 32px 9px 32px" valign="top" rowspan="1" colspan="1" align="left">

                <div>
                  <br>
                  <p style="text-align:justify;text-justify:inter-word;">Dear <?php echo $this->name ?>,</p>

                  <p style="text-align:justify;text-justify:inter-word;">Thank you very much for using OSEHRA Technical Journal!</p>

                  <p style="text-align:justify;text-justify:inter-word;">The submission is currently under review. It will be made public once it is approved</p>
                  <p style="text-align:justify;text-justify:inter-word;">Meanwhile, you can still access the submission
                    <a style="color:#ee5624;font-family:Arial,Helvetica,sans-serif;font-weight:bold;font-size:10pt"
                       shape="rect" href="<?php echo $this->webroot . $this->link ?> " target="_blank">here</a>
                  </p>

                  <p style="text-align:justify;text-justify:inter-word;">OSEHRA Technical Journal.</p>
                <br/>
              </td>
            </tr>
          </tbody>
        </table>


      </td>

    </tr>
  </tbody>
</table>
