<?php
$this->headScript()->appendFile($this->webroot . '/privateModules/reviewosehra/public/js/submit/submit.index.js');
?>
<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/reviewosehra/public/css/submit/submit.index.css" rel="stylesheet" />

<h2>Review an article</h2>
<h3>Title: <?php echo $this->resource->getName() ?> </h3>
<div class="abstract" style="text-align: justify;"><?php echo str_replace("<br>", "<br/>", nl2br($this->resource->getDescription())) ?></div>

<br/>

<div id="reviewWrapper">
  <table>
    <tr>
      <td id="tdLeftPanel">
        <div id="divLeftPanel">
          <h4><?php echo ($this->listArray['list']['type'] == OSERHAREVIEW_LIST_PEERREVIEW) ? "Peer Review": "Final Review"?></h4>
          <p id="descriptionQuestionList">

          </p>
          <p >
            Text about the certifications levels.
          </p>
          <h4>Summary</h4>
          <table id="summaryTable">
            <thead>
              <tr>
                <th>Topic</th>
                <th>Completed</th>
              </tr>
            </thead>
            <tbody>
              
            </tbody>
            <tfoot>
              <tr id="summaryProgress">
                <td colspan="3">
                  <progress value="0" max="100"></progress>
                </td>
              </tr>
            </tfoot>
          </table>
          <h4>Comments</h4>
          <textarea 
            <?php
            if(!$this->isEditable)echo 'readonly';
            ?> 
            id="globalComment"></textarea>
          <h4>Recommended Certification Level
          <select id="certificationLevel"
            <?php
            if(!$this->isEditable)echo 'readonly';
            ?> >
            <option></option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
          </select>
          </h4>
          
          <?php
          if($this->isEditable)echo ' <input id="saveReview" type="button" value="Save"/>';
          ?>
        </div>
      </td>
      <td id="tdRightPanel">
        <div id="divRightPanel">
          <h4>Topics: <select id="listTopics">

          </select></h4>
          <div id="templateQuestion" style="display:none;">
            <div class="selectMultipleWrapper">
              <select <?php   if(!$this->isEditable)echo 'disabled="disabled"';  ?> multiple size=4>
                <option value="<?php echo OSERHAREVIEW_REVIEW_LOW ?>">Low</option>
                <option value="<?php echo OSERHAREVIEW_REVIEW_MEDIUM ?>">Medium</option>
                <option value="<?php echo OSERHAREVIEW_REVIEW_HIGH ?>">High</option>
                <option value="<?php echo OSERHAREVIEW_REVIEW_NA ?>">N/A</option>
              </select>
            </div>
            <span class="questionDescription">{description}</span><br/>
            Comment: <textarea <?php   if(!$this->isEditable)echo 'readonly';  ?> ></textarea><br/>
          </div>
        </div>        
      </td>
    </tr>
  </table>  
</div>
