<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/submit/submit.index.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/dynatree/jquery.dynatree.min.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/fancyapp/source/jquery.fancybox.pack.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/iCheck-master/jquery.icheck.min.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/parsley.min.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/jquery.dynamiclist.min.js');
?>
<LINK rel="stylesheet" type="text/css" href="<?php echo $this->webroot ?>/privateModules/journal/public/js/lib/fancyapp/source/jquery.fancybox.css">
<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/journal/public/css/submit/submit.index.css" rel="stylesheet" />
<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/journal/public/js/lib/dynatree/skin/ui.dynatree.css" rel="stylesheet" />

<div class="viewMain">
  <h3>Manage Submission</h3>
  <div id="submission">

    <form action="" method="POST" id="submitForm" data-validate="parsley">
      <table width="100%"  border="0">
        <tr>
          <td>
            <div class="submission">
              <div class="title">Title <span style="color:#A60000;">*</span></div>
              <div class="caption">Main title of your submission</div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <textarea class="smallInput" data-required="true" data-rangelength="[1,200]" name="title"><?php echo $this->resource->getName() ?></textarea>
          </td>
        </tr>       
          
        <tr>
          <td>
            <div class="submission">
              <div class="title">Authors <span style="color:#A60000;">*</span></div>
              <div class="caption"></div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <div id="authors">

                <?php
                $authors = $this->resource->getAuthors();
                if(empty($authors)) $authors = array(array('', ''));
                foreach($authors as $key => $author)
                  {
                  echo '<div class="list-item"><input type="text" name="firstname['.$key.'].a" data-required="true" style="width:150px;" placeholder="Firstname" value="'.$author[0].'"/>
                  <input type="text" name="lastname['.$key.'].b" data-required="true" style="width:150px;" placeholder="Lastname" value="'.$author[1].'"/>
                  <a href="#" class="list-remove">Remove</a></div>';
                  }
                ?>

              <a href="#" class="list-add">Add an author</a>
            </div>
          </td>
        </tr>     
        <tr>
          <td>
            <div class="submission">
              <div class="title">Institution <span style="color:#A60000;">*</span></div>
              <div class="caption">Institution of the principal author</div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <textarea class="smallInput" data-required="true" name="institution"><?php echo $this->resource->getInstitution() ?></textarea>
          </td>
        </tr>      
        <tr>
          <td>
            <div class="submission">
              <div class="title">Abstract <span style="color:#A60000;">*</span></div>
              <div class="caption"></div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <textarea class="bigInput" data-required="true" name="description"><?php echo $this->resource->getDescription() ?></textarea>
          </td>
        </tr>
        <tr>
          <td>
            <div class="submission">
              <div class="title">Related work </div>
              <div class="caption">Describe if your article has some references to previously published papers by other</div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <textarea class="bigInput"  name="related"><?php echo $this->resource->getRelated() ?></textarea>
          </td>
        </tr>
        <tr>
          <td>
            <div class="submission">
              <div class="title">Type of submission <span style="color:#A60000;">*</span></div>
              <div class="caption"></div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <select name="type" data-required="true">
              <option value="<?php echo RESOURCE_TYPE_NOT_DEFINED ?>" <?php if ($this->resource->getType() == RESOURCE_TYPE_NOT_DEFINED) echo "selected"; ?>></option>
              <option value="<?php echo RESOURCE_TYPE_SOFTWARE ?>" <?php if ($this->resource->getType() == RESOURCE_TYPE_SOFTWARE) echo "selected"; ?>>Software</option>
              <option value="<?php echo RESOURCE_TYPE_PLUGIN ?>" <?php if ($this->resource->getType() == RESOURCE_TYPE_PLUGIN) echo "selected"; ?>>Plugin</option>
              <option value="<?php echo RESOURCE_TYPE_PUBLICATION ?>" <?php if ($this->resource->getType() == RESOURCE_TYPE_PUBLICATION) echo "selected"; ?>>Publication</option>
              <option value="<?php echo RESOURCE_TYPE_TUTORIAL ?>" <?php if ($this->resource->getType() == RESOURCE_TYPE_TUTORIAL) echo "selected"; ?>>Tutorial</option>
              <option value="<?php echo RESOURCE_TYPE_DATASET ?>" <?php if ($this->resource->getType() == RESOURCE_TYPE_DATASET) echo "selected"; ?>>Dataset</option>
            </select>
          </td>
        </tr>
        
        <tr>
          <td>
            <div class="submission">
              <div class="title">Category <span style="color:#A60000;">*</span></div>
              <div class="caption">Please select one or multiple categories</div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <div id="treeWrapper" style="width: 700Px;"></div>
            <div id="treeInputs" style="display:none;"></div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="submission">
              <div class="title">Tags</div>
              <div class="caption"></div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <?php
            $value = join(", ", $this->resource->getTags());
            if (count($this->resource->getTags()) > 0)
              {
              $value .= ", ";
              }
            ?>
            <div id="tags">
                <?php
                $tags = $this->resource->getTags();
                if(empty($tags)) $tags = array('');
                foreach($tags as $key => $tag)
                  {
                  echo '<div class="list-item"><input type="text" name="tag['.$key.'].tag" data-required="true" style="width:150px;" placeholder="Tag" value="'.$tag.'"/>
                <a href="#" class="list-remove">Remove</a></div>';
                  }
                ?>
              <a href="#" class="list-add">Add a tag</a>
            </div>
          </td>
        </tr>   
        <tr>
          <td>
            <div class="submission">
              <div class="title">Copyright and Disclaimer</div>
              <div class="caption"></div>
            </div>
          </td>
        </tr>
        <tr>
          <td id="copyrightWrapper">            
            <?php
            if(!$this->resource->saved)
              {?>
              <span>Do you have the permission to submit the content of this article? <span style="color:#A60000;">*</span></span>
                  <input type="radio" data-required="true" name="permission" id="PubPermissionsYes" value="yes"><label style="" for="PubPermissionsYes">Yes</label>
                  <input type="radio" data-required="true" name="permission" id="PubPermissionsNo" value="no"><label for="PubPermissionsNo">No</label>
              <br/>
              <span>Do you accept the <a href="http://www.osehra.org/document/corporate-contributor-licensing-agreement-v3" target="_blank">Contributor Licensing Agreement</a>? <span style="color:#A60000;">*</span></span>
                  <input type="radio" data-required="true" name="cla" id="PubClaYes" value="yes"><label style="" for="PubClaYes">Yes</label>
                  <input type="radio" data-required="true" name="cla" id="PubClaNo" value="no"><label for="PubClaNo">No</label><br/>
             <?php
              }?>
            <span>Copyright holder:</span>
            <textarea class="smallInput" style ="width:400px;" name="copyright"><?php echo $this->resource->getCopyright() ?></textarea><br/>
            <span>Grant/Tracking number:</span>
            <textarea class="smallInput" style ="width:400px;" name="grant"><?php echo $this->resource->getGrant() ?></textarea><br/>
            <span>Select a disclaimer:</span>
            <select name="disclaimer">
              <option value="-1" <?php if ($this->resource->getDisclaimer() == -1) echo "selected"; ?>>No disclaimer</option>
              <?php
              foreach($this->disclaimers as $diclaimer)
                {
                echo '<option value="'.$diclaimer->getKey().'" ';
                if ($this->resource->getDisclaimer() == $diclaimer->getKey()) echo "selected"; 
                echo ">".$diclaimer->getName()."</option>";
                }?>
            </select>
            <br/>
            <?php
            foreach($this->disclaimers as $diclaimer)
              {
              echo '<textarea class="disclaimer_description" style="display:none;width:895px;height:50px" id="disclaimer_description_'.$diclaimer->getKey().'">'.$diclaimer->getDescription().'</textarea>';
              }?>
          </td>
        </tr>

        <tr>
          <td>
            <br/>
            <input type="submit" style="width:150px;" value="Next >"/>
          </td>
        </tr>                
      </table>
    </form>
  </div>
</div>

<div id="licenseWrapper" style="display:none;">

  <br>
  <div align="center"><font size="+1"><strong>License</strong></font></div>
  <br>

  <pre>You are licensing your work to OSEHRA Inc. under the 
Creative Commons Attribution License Version 3.0.

You agree to the following:

OSEHRA is free
    * to copy, distribute, display, and perform the work
    * to make derivative works
    * to make commercial use of the work

Under the following conditions:
"by Attribution" - OSEHRA must attribute the work in the manner specified by the author or licensor.

    * For any reuse or distribution, they must make clear to others the license terms of this work.
    * Any of these conditions can be waived if they get permission from the copyright holder.

Your fair use and other rights are in no way affected by the above.

This is a human-readable summary of the Legal Code (the full license) available at
http://creativecommons.org/licenses/by/3.0/legalcode</pre>

  <br>
  <table style="width:300px;margin:auto;">
    <tbody><tr>
        <td> <a href="#" onclick="$.fancybox.close();">I Grant the Licence</a></td>
        <td>|</td>
        <td><div align="center"><a href="<?php echo $this->webroot?>/journal">I Do Not Grant the Licence </a></div></td>
        
      </tr>
    </tbody></table>
</div>

