<?php
$this->headScript()->appendFile($this->webroot . '/privateModules/reviewosehra/public/js/submit/submit.index.js');
?>
<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/reviewosehra/public/css/submit/submit.index.css" rel="stylesheet" />

<h2>Review an article</h2>
<h3>Title: <?php echo $this->resource->getName() ?> </h3>
<div class="abstract" style="text-align: justify;"><?php echo str_replace("<br>", "<br/>", nl2br($this->resource->getDescription())) ?></div>

<br/>

<div id="reviewWrapper">
  <table>
    <tr>
      <td id="tdLeftPanel">
        <div id="divLeftPanel">
          <h4><?php echo ($this->listArray['list']['type'] == OSERHAREVIEW_LIST_PEERREVIEW) ? "Peer Review": "Final Review"?></h4>
          <p>
            <?php echo $this->listArray['list']['description'] ?>
          </p>
          <p>
            Text about the certifications levels.
          </p>
        </div>
      </td>
      <td id="tdRightPanel">
        <div id="divRightPanel">
          <h4>Topics: <select id="listTopics">

          </select></h4>
          <div id="templateQuestion" style="display:none;">
            <div class="selectMultipleWrapper">
              <select multiple size=4>
                <option value="<?php echo OSERHAREVIEW_REVIEW_LOW ?>">Low</option>
                <option value="<?php echo OSERHAREVIEW_REVIEW_MEDIUM ?>">Medium</option>
                <option value="<?php echo OSERHAREVIEW_REVIEW_HIGH ?>">High</option>
                <option value="<?php echo OSERHAREVIEW_REVIEW_NA ?>">N/A</option>
              </select>
            </div>
            {description}<br/>
            Comment: <textarea></textarea><br/>
            Attach a file: <input type="file"/>
          </div>
        </div>        
      </td>
    </tr>
  </table>  
</div>
