<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/submit/submit.selectissue.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/dynatree/jquery.dynatree.min.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/fancyapp/source/jquery.fancybox.pack.js');
?>
<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/journal/public/css/submit/submit.index.css" rel="stylesheet" />
<LINK rel="stylesheet" type="text/css" href="<?php echo $this->webroot ?>/privateModules/journal/public/js/lib/fancyapp/source/jquery.fancybox.css">
<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/portal/public/js/lib/dynatree/skin/ui.dynatree.css" rel="stylesheet" />

<div class="viewMain">
  <h3>Choose a journal where to submit</h3>
  <div id="submission">

    <br/>
    You don't know how to submit your paper ? You need some help ? Go to the <a href="<?php echo $this->webroot ?>/journal/help">help page</a> or download  an  <a href="<?php echo $this->webroot ?>/privateModules/journal/public/InsightJournalSubmissionTemplate.tgz">example</a>.
    <br/>
    <table width="70%"  border="0">
      <tr>
        <td width="15%" ><div align="left"><strong>Journal</strong></div></td>
        <td width="50%" ><div align="left"><strong>Title</strong></div></td>
        <td width="10%" ><div align="left"><strong>Days left</strong></div></td>
        <td width="20%" ><div align="left"><strong>Actions</strong></div></td>
      </tr>
      <tr>
        <td height="1" colspan="4"><hr></td>
      </tr>
      <?php
      foreach($this->issues as $key => $issue)
        {
        $community = MidasLoader::loadModel("Folder")->getCommunity(MidasLoader::loadModel("Folder")->getRoot($issue));
       $day1 = new Zend_Date(strtotime($issue->getPaperdueDate()));
        $day2 = new Zend_Date();
        echo"
        <tr >
        <td>".$community->getName()."</td>
        <td><a href=" . $this->webroot . "/journal/submit/?issue=" . $issue->getKey() . ">" . $issue->getName()."</a>";
        if($issue->getDefaultPolicy() == 1)
          {
          echo " (Private issue)";
          }          
        echo "</td>";
        echo"<td>" . $day2->sub($day1)->toString(Zend_Date::DAY) . "</td>";
        echo "<td>";
        echo "<a href=" . $this->webroot . "/journal/submit/?issue=" . $issue->getKey() . ">Select issue</a>, ";
        echo "<a class='issuePage' href='".$this->webroot."/journal/view/issue?folderId=".$issue->getKey()."'>Show details</a>";
        echo "</td>";

        echo "</tr>";
        }
      ?>

      <br/>
    </table>
    <p>&nbsp;</p>
  </div>
