<?php
/* =========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * ========================================================================= */
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/submit/submit.upload.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/dynatree/jquery.dynatree.min.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/jQuery-File-Upload-8.4.0/js/jquery.iframe-transport.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/jQuery-File-Upload-8.4.0/js/jquery.fileupload.js');
?>
<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/journal/public/css/submit/submit.upload.css" rel="stylesheet" />
<link rel="stylesheet" href="<?php echo $this->webroot ?>/privateModules/journal/public/js/lib/jQuery-File-Upload-8.4.0/css/jquery.fileupload-ui.css">

<div class="viewMain">
  <h3>Manage files.</h3>

  <p>This article will be assigned the following handle: http://hdl.handle.net/<?php echo $this->resource->getHandle()?>. Note that the handle will be activated only when the article is accepted for publication.
  </p>
  <p>
    The purpose of this page is to upload the documents and datasets related to your article. You can also upload a Logo which will be shown on the article's page.
  </p>


  <b>What type of file to you want to upload? </b>
  <select id="typeFile">
    <option></option>
    <option value="<?php echo BITSTREAM_TYPE_THUMBNAIL ?>">Thumbnail (Logo)</option>    
    <option value="<?php echo BITSTREAM_TYPE_PAPER ?>">Paper</option>    
    <option value="<?php echo BITSTREAM_TYPE_SOURCECODE ?>">Source Code</option>    
    <option value="<?php echo BITSTREAM_TYPE_SOURCECODE_GITHUB ?>">Github repository</option>    
    <option value="<?php echo BITSTREAM_TYPE_DATA ?>">Data</option>    
    <option value="<?php echo BITSTREAM_TYPE_MIST ?>">Other</option>    
  </select><br/><br/>
  <div id='uploadContentBlock' style="display:none;width:700px;">
    <!-- The fileinput-button span is used to style the file input field as button -->
    <span class="btn btn-success fileinput-button">
      <i class="icon-plus icon-white"></i>
      <span>Select files...</span>
      <!-- The file input field used as target for the file upload widget -->
      <input id="fileupload" type="file" name="files[]" multiple> 
    </span>

    <!-- The global progress bar -->
    <div id="progress" style="display:none;width: 200px;" class="progress progress-success progress-striped">
      <div class="bar"></div>
    </div>
    <br/>
    <br/>
  </div>
  <div id='githubContentBlock' style="display:none;width:700px;">
    <label>Set github URL (for example: https://github.com/midasplatform/Midas):</label>
    <input type="text" style="width: 400px;" id="github" name="github"/>
    <input type="button" id="addGithub" value="Add"/>
    <br/>
    <br/>
  </div>

  <?php
  if (count($this->bitstreams) != 0)
    {
    echo "<b>Uploaded files</b><br/>";
    echo "
       <table id='uploadedFiles'
            <thead>
              <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>";
    

    $typeToString = array(
        BITSTREAM_TYPE_THUMBNAIL => "Thumbnail (Logo)",
        BITSTREAM_TYPE_PAPER => "Paper",
        BITSTREAM_TYPE_SOURCECODE => "Source Code",
        BITSTREAM_TYPE_SOURCECODE_GITHUB => "Github repository",
        BITSTREAM_TYPE_DATA => "Data",
        BITSTREAM_TYPE_MISC => "Other",
    );

    foreach ($this->bitstreams as $bitstream)
      {
      $type = MidasLoader::loadComponent("Bitstream", "journal")->getType($bitstream);
      if (!$type)
        $type = BITSTREAM_TYPE_MISC;
      echo "
        <tr key='" . $bitstream->getKey() . "'>
        <td>" . $bitstream->getName() . "</td><td>" . $typeToString[$type] . "</td><td><a href='#' class='deleteLink'>Delete</a></td>";
      }
    echo "</tbody>
I have the right to distribute these files
          </table>";
    ?>
    <br/>
    <input type="checkbox" class="checkbox" id="acceptRights" value="1">
    <label style="display:inline;" for="acceptRights"> I certify that I have the right to distribute these files.</label>
    <br/>
    <input type="checkbox" class="checkbox" id="acceptLicense" value="0" <?php if ($this->resource->getSourceLicense()) echo "checked='true'";?>>
    <label style="display:inline;" for="acceptLicense"> I certify that all source code files/repositories uploaded here are under Apache 2 License (optional).</label>
    <br/>

    <form action="" method="POST">
      <?php
      if ($this->isPrivate && !$this->isAdmin)
        {
        echo '<input type="submit" disabled="disabled" name="finish"  value="Submit for Approval >"/>';
        }
      elseif ($this->isPrivate && !$this->isAdmin)
        {
        echo '<input type="submit" disabled="disabled" name="finish"  value="Approve >"/>';
        }
      else
        {
        echo '<input type="submit" disabled="disabled" name="finish"  value="Publish >"/>';
        }
      ?>

      <?php
      }
    ?>

      <input name="source-license" type="hidden" id="hiddenSourceLicense" value='0'/> 
  </form>
</div> 
