<?php
/* =========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * ========================================================================= */
?>

<h3>Notifications:</h3>

<h3>TBD</h3>

<form method="post" class="genericForm" action=""><fieldset style="display:none;"><input type="hidden" name="_method" value="POST"></fieldset><br>
  <table width="100%" height="119" border="0">
    <tbody>

      <tr>
        <td height="2">Receive email when there is a new submission in a new journal:
          <input type="radio" name="NewSubmissionEmail" value="1" checked="">
          Yes
          <input type="radio" name="NewSubmissionEmail" value="0">
          No
        </td>
      </tr>

      <tr>
        <td height="17" valign="top">Receive email when there is a new review for my publications:
          <input type="radio" name="NewReviewsEmail" value="1" checked="">
          Yes
          <input type="radio" name="NewReviewsEmail" value="0">
          No</td>
      </tr>
      <tr>
        <td height="17" valign="top">Email preferences:
          <input type="radio" name="EmailPref" value="0" checked="">
          HTML
          <input type="radio" name="EmailPref" value="1">
          Plain text </td>
      </tr>
      
      <tr>
        <td>&nbsp;&nbsp;&nbsp;
          <input name="submit" type="submit" id="submit" value="Save">
        </td></tr>
    </tbody></table>

  <br><br>

</form>