<?php
/* =========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * ========================================================================= */

echo '<script type="text/javascript" src="' . $this->webroot . '/privateModules/journal/public/js/config/config.notification.js"></script>';
?>

<h3>Notifications:</h3>

<form method="post" class="genericForm" id="notificationForm" action="<?php echo $this->webroot?>/journal/user/notification">

  <table width="100%" height="119" border="0">
    <tbody>

      <tr>
        <td height="2">Receive email when there is a new submission in a new journal:
          <input type="radio" name="NewSubmissionEmail" value="1" <?php if($this->status[0] == 1) echo "checked='checked'"?>>
          Yes
          <input type="radio" name="NewSubmissionEmail" value="0" <?php if($this->status[0] == 0) echo "checked='checked'"?>>
          No
        </td>
      </tr>

      <tr>
        <td height="17" valign="top">Receive email when there is a new review for my publications:
          <input type="radio" name="NewReviewsEmail" value="1" <?php if($this->status[1] == 1) echo "checked='checked'"?>>
          Yes
          <input type="radio" name="NewReviewsEmail" value="0" <?php if($this->status[1] == 0) echo "checked='checked'"?>>
          No</td>
      </tr>
            
      <tr>
        <td>&nbsp;&nbsp;&nbsp;
          <input name="submit" type="submit" id="submitNotificationForm" value="Save">
        </td></tr>
    </tbody></table>

  <br><br>

</form>