<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/user/user.register.js');
?>
<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/webviz/public/css/user/user.register.css" rel="stylesheet" />
<div class="loginElement">
      

  
</div>

