<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/user/user.settings.js');
?>
<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/journal/public/css/user/user.settings.css" rel="stylesheet" />

<h3>Profile</h3>

<?php
if(isset($this->userId))echo $this->action("settings", "user-core", "journal", array("userId" => $this->userId));
else echo $this->action("settings", "user-core", "journal", array("userId" => $this->userId));
?>
