<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/index/index.index.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/dynatree/jquery.dynatree.min.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/dodotdot.1.5.9.js');
?>
<link type="text/css" href="<?php echo $this->webroot?>/privateModules/journal/public/css/index/index.index.css" rel="stylesheet" />
<link type="text/css" href="<?php echo $this->webroot?>/privateModules/journal/public/js/lib/dynatree/skin/ui.dynatree.css" rel="stylesheet" />
<div class="ContentWithLeftPanel">
  <div class="Panel box">
    <h3 class="FilterH3">Filters:</h3>
    <div class="FiltersPanel">
      <div id="treeWrapper"></div>
    </div>
    <?php
    if(isset($this->issues))
      {
      echo '<h3 style="margin-top:10px;" class="FilterH3">Issues:</h3>';
      foreach($this->issues as $issue)
        {
        echo "<div class='issueButton' key='".$issue->getKey()."'>";
        if($issue->active)
          {
          echo "<div qtipconditionnal=\"".$issue->getName()."\" class='issueTitle issueActive'>".$issue->getName()."</div>";
          echo "<div class='issueSubTitle'>Active: ".date("m.d.y", strtotime($issue->getPaperdueDate()))." (Paperdue)</div>";
          }
        else
          {
          echo "<div qtipconditionnal=\"".$issue->getName()."\" class='issueTitle'>".$issue->getName()."</div>";
          echo "<div class='issueSubTitle'>Completed</div>";
          }
        echo "</div>";
        }
      }
      ?>
    <div style="margin:5px;" class="SearchCount"></div>
    <img id="searchLoadingImg" src="<?php echo $this->webroot?>/core/public/images/icons/loading-small.gif"/>
  </div>
  
  <div class="MainContent">
    <div class="SearchResultsHeader">     
    </div>
    
    <div class="SearchResults">
      
    </div>    
    <script type="text/template" id="SearchResultTemplate">
      <div class="SearchResultEntry box" id="{id}">
        <div class="ResultTop">
          <a class="resourceLink" href="<?php echo $this->webroot?>/journal/view/{id}"></a>
          <img class="ResultLogo" src="<?php echo $this->webroot?>/privateModules/journal/public/images/typeIcon/{type}.png" />
          <span class="ResultTitle">{title}</span>          
        </div>
        <div class="ResultAuthors">
          {authors}
        </div>
        <div class="ResultDescription">
          {description}
        </div>
        <div class="ResultSubDescription">
          {statistics}, {rating} stars
        </div>
      </div>
    </script>
  </div>  
</div>

