<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/reviewosehra/public/css/index/index.index.css" rel="stylesheet" />
<h4>Reviews</h4>
<?php
if (empty($this->reviews))
  {
  echo "There is no review at this time.<br/>";
  if ($this->logged)
    {
    echo "Be the first to <a href=\"" . $this->webroot . "/reviewosehra/submit/?revision_id=" . $this->resource->getRevision()->getKey() .
    "\">review this publication!</a>";
    }
  else
    {
    echo "To submit one, please log in.";
    }
  }
else
  {
  foreach ($this->reviews as $key => $review)
    {    
    foreach ($review['complete'] as $r)
      {
      showReviews($r, $this->webroot);
      }
    foreach ($review['notcomplete'] as $r)
      {
      showReviews($r, $this->webroot);
      }
    }

  if ($this->logged)
    {
    echo "<p><a href=\"" . $this->webroot . "/reviewosehra/submit/?revision_id=" . $this->resource->getRevision()->getKey() .
    "\">Review this publication!</a></p>";
    }
  else
    {
    echo "<p>To submit a review, please log in.</p>";
    }
  }

function showReviews($review, $webroot)
  {
  echo "<p><a href='".$webroot."/reviewosehra/submit?review_id=".$review->getKey()."'>".(($review->getType() == OSERHAREVIEW_LIST_PEERREVIEW)? "Peer":"Final")." review by ".$review->getUser()->getFullName()."</a>:</p>";
  echo "<table class='reviewTable'>";
  echo $review->getCacheSummary();
  echo "</table><br/>";
  }