<?php
$this->headScript()->appendFile($this->webroot . '/privateModules/reviewosehra/public/js/index/index.index.js');
?>
<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/reviewosehra/public/css/index/index.index.css" rel="stylesheet" />
<?php
  $phaseConvert = array(OSERHAREVIEW_LIST_PEERREVIEW => "Peer",
       OSERHAREVIEW_LIST_FINALREVIEW => "Final",
       OSERHAREVIEW_LIST_COMPLETE => "Complete");

  $phase = $phaseConvert[$this->reviewPhase];
  $hasSubmitterAReview = false;
?>

<h4>Reviews (Phase: <?php echo $phase?>)</h4>
<?php
if (empty($this->reviews))
  {
  echo "There is no review at this time.<br/>";
  if ($this->logged)
    {
    echo "Be the first to <a href=\"" . $this->webroot . "/reviewosehra/submit/?revision_id=" . $this->resource->getRevision()->getKey() .
    "\">review this publication!</a>";
    }
  else
    {
    echo "To submit one, please log in.";
    }
  }
else
  {
  foreach ($this->reviews as $key => $review)
    {   
    foreach ($review['complete'] as $r)
      {
      if($this->logged && $r->getType() == $this->reviewPhase && $r->getUserId() == $this->userDao->getKey())
        {
        $hasSubmitterAReview = true;
        }
      if($r->getType() != $this->reviewPhase && ($phase!="Complete")) echo "<div class='hiddenReview'>";
      showReviews($r, $this->webroot);
      if($r->getType() != $this->reviewPhase) echo "</div>";
      }
    foreach ($review['notcomplete'] as $r)
      {
      if($this->logged && $r->getType() == $this->reviewPhase && $r->getUserId() == $this->userDao->getKey())
        {
        $hasSubmitterAReview = true;
        }
      if($r->getType() != $this->reviewPhase && ( $phase!="Complete")) echo "<div class='hiddenReview'>";
      showReviews($r, $this->webroot);
      if($r->getType() != $this->reviewPhase) echo "</div>";
      }
    }
    
  echo "<a id='hiddenReviewlink'></a>";

  if(!$hasSubmitterAReview && $this->logged && (
          $this->reviewPhase == OSERHAREVIEW_LIST_PEERREVIEW
          || $this->isAdmin))
    {
    echo "<p><a href=\"" . $this->webroot . "/reviewosehra/submit/?revision_id=" . $this->resource->getRevision()->getKey() .
    "\">Review this publication!</a></p>";
    }
  elseif(!$hasSubmitterAReview && $this->reviewPhase == OSERHAREVIEW_LIST_PEERREVIEW)
    {
    echo "<p>To submit a review, please log in.</p>";
    }
  }

function showReviews($review, $webroot)
  {
  echo "<p style='margin:0;'><a href='".$webroot."/reviewosehra/submit?review_id=".$review->getKey()."'>".(($review->getType() == OSERHAREVIEW_LIST_PEERREVIEW)? "Peer":"Final")." review by ".$review->getUser()->getFullName()."</a>:</p>";
  echo "<table class='reviewTable'>";
  echo $review->getCacheSummary();
    $contentArray = JsonComponent::decode($review->getContent());
  if(isset($contentArray['list']['certificationLevel']) && is_numeric($contentArray['list']['certificationLevel']))
    {
    echo "<tr><td>Recommended Certification Level</td><td>".$contentArray['list']['certificationLevel']."</td></tr>";
    }
  echo "</table>";

  echo "<br/>";
  }