<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/

class Journal_UserCoreController extends Journal_AppController
{
  /** Recover the password (ajax) */
  function recoverpasswordAction()
    {
    if($this->logged)
      {
      throw new Zend_Exception('Shouldn\'t be logged in');
      }
    $this->disableLayout();
    $email = $this->_getParam('email');
    if(isset($email))
      {
      $this->disableView();
      $user = MidasLoader::loadModel("User")->getByEmail($email);

       // Check ifthe email is already registered
      if(!$user)
        {
        echo JsonComponent::encode(array(false, $this->t('No user registered with that email.')));
        exit;
        }

      $notifications = Zend_Registry::get('notifier')->callback('CALLBACK_CORE_RESET_PASSWORD', array('user' => $user));
      foreach($notifications as $module => $result)
        {
        if($result['status'] === true)
          {
          echo JsonComponent::encode(array(true, $result['message']));
          return;
          }
        }

      $pass = UtilityComponent::generateRandomString(10);
      MidasLoader::loadModel("User")->changePassword($user, $pass);

      // Send the email
      $url = $this->getServerURL().$this->view->webroot;

      $text = "Hello,<br><br> You have asked for a new password for the OSEHRA Tehcnical Journal.<br>";
      $text .= "Please go to this page to log and change your password:<br>";
      $text .= "<a href=\"".$url."\">".$url."</a><br>";
      $text .= "Your new password is: ".$pass."<br>";
      $text .= "<br><br>Generated by the OSEHRA Tehcnical Journal";

      if($this->isTestingEnv() || mail("$email", "OSEHRA Tehcnical Journal: Password request", "$text", "From: \nReply-To: no-reply\nX-Mailer: PHP/" . phpversion()."\nMIME-Version: 1.0\nContent-type: text/html; charset = UTF-8"))
        {
        MidasLoader::loadModel("User")->save($user);
        echo JsonComponent::encode(array(true, $this->t('An Email has been sent to').' '.$email));
        }
      else
        {
        echo JsonComponent::encode(array(false, $this->t('Problem during process !')));
        }
      }
    } // end recoverpassword

  function settingsAction()
    {    
    $request = $this->getRequest();
    $response = $this->getResponse();
    include_once BASE_PATH.'/core/controllers/UserController.php';
    $name = "UserController";
    $controller = new $name($request, $response);
    $controller->userSession = $this->userSession;
    $controller->logged = $this->logged;
    $actionName = 'settingsAction';
    $controller->$actionName();
    if($this->_request->isPost())
      {
      $this->disableView();
      }
    else
      {
      $this->view->setScriptPath(BASE_PATH."/core/views");
      $this->render('user/settings', null, true);
      }
    } // end method indexAction
 
}//end class
