<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/view/view.download.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/fancyapp/source/jquery.fancybox.pack.js');
?>

<LINK rel="stylesheet" type="text/css" href="<?php echo $this->webroot ?>/privateModules/journal/public/js/lib/fancyapp/source/jquery.fancybox.css">


<div>
  <h3>Download</h3>
  <a href="<?php echo $this->webroot?>/journal/view/?revisionId=<?php echo $this->resource->getRevision()->getKey()?>">Back to article</a>
  <br/>
  <br/>

  <?php
     // Check for the presence of a completed recaptcha in
     //  the form of a g-recaptcha-response parameter
     // if none, show the recaptcha
    if(!$_POST['g-recaptcha-response']) {
        echo '  <form id="captchaform" method="POST" action="" name="input">
                   <div class="g-recaptcha" data-sitekey="6LdgUw4UAAAAAAFQWVY8dLlwvnGaiEu7YCDIw51s"></div>
                   <input id="verifyHuman" type="submit" value="Verify"></submit>
                </form>';
    }
    // If it does exist
    else {
      // Query the google server for verification
      $url = "https://www.google.com/recaptcha/api/siteverify";
      $url = $url."?secret=".MidasLoader::loadModel("Setting")->getValueByName('captchaSecret', "journal");;
      $url = $url."&response=".$_POST['g-recaptcha-response'];
      // Use cURL to query Google for validation.
      $curl = curl_init();
      curl_setopt($curl, CURLOPT_URL, $url);
      curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
      curl_setopt($curl, CURLOPT_TIMEOUT, 15);
      curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, TRUE);
      curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, TRUE);
      $curlData = curl_exec($curl);
      curl_close($curl);
      $res = json_decode($curlData, TRUE);

      if($res['success'] == TRUE) {
        // TRUE means that the query was verified and we have a user, show them the links
        $size = 0;
        $bitstreams = $this->resource->getRevision()->getBitstreams();
        foreach ($bitstreams as $bitstream)
          {
          $size += $bitstream->getSizebytes();
          }
        echo '<ul style="display">
                <li><a href='.$this->webroot.'/download?items='.$this->resource->getKey().','.$this->resource->getRevision()->getRevision().'>Download All</a>
                ('.MidasLoader::loadComponent("Utility")->formatSize($size).')</li>';
        if($this->paper)
          {
          echo '<li><a href='.$this->webroot.'/download?bitstream='.$this->paper->getKey() /'">Download Paper</a>
        </li>';
          }
        echo '</ul>';
      }
      else {
          // Something didn't work right, try again
          echo "The RECAPTCHA was unable to be verified.  Please try again:";
          echo '  <form id="captchaform" method="POST" action="" name="input">
                   <div class="g-recaptcha" data-sitekey="6LdgUw4UAAAAAAFQWVY8dLlwvnGaiEu7YCDIw51s"></div>
                   <input id="verifyHuman" type="submit" value="Verify"></submit>
                </form>';
      }
};
 ?>
</div>

<?php
  $disclaimerIndex = MidasLoader::loadModel("Setting")->getValueByName('licenseDisclaimer', "journal");
  $disclaimer = MidasLoader::loadModel("Disclaimer", "journal")->load($disclaimerIndex);
  if($disclaimer && $_POST['g-recaptcha-response'] )
    {
    echo '<div id="disclaimerWrapperLicense" style="display:none;width:700px;"><h4>Disclaimer</h4>';
    echo "<pre style='word-break:unset'>".$disclaimer->getDescription()."</pre>";
    echo "<br>
      <table style='width:140px;margin:auto;'>
        <tbody><tr>
           <td> <a href='#' onclick='$.fancybox.close();'>Acknowledged</a></td>
              <td>|</td>
               <td><div align='center'><a href='".$this->webroot."/journal/view/?revisionId=".$this->resource->getRevision()->getKey()."'>Back</a></div></td>
          </tr>
        </tbody></table>";
    echo "</div>";
    }

if(($this->resource->getDisclaimer() != -1) && $_POST['g-recaptcha-response'])
  {
  $disclaimer = MidasLoader::loadModel("Disclaimer", "journal")->load($this->resource->getDisclaimer());
  if($disclaimer)
    {
    echo '<div id="disclaimerWrapper" style="display:none;width:700px;"><h4>Disclaimer</h4>';
    echo "<pre style='word-break:unset'>".$disclaimer->getDescription().'</pre>';
    echo "<br>
      <table style='width:140px;margin:auto;'>
        <tbody><tr>
           <td> <a href='#' onclick='$.fancybox.close();'>Agree</a></td>
              <td>|</td>
               <td><div align='center'><a href='".$this->webroot."/journal/view/?revisionId=".$this->resource->getRevision()->getKey()."'>Decline</a></div></td>
          </tr>
        </tbody></table>";
    echo "</div>";
    }
  }
