<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/view/view.download.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/fancyapp/source/jquery.fancybox.pack.js');
?>

<LINK rel="stylesheet" type="text/css" href="<?php echo $this->webroot ?>/privateModules/journal/public/js/lib/fancyapp/source/jquery.fancybox.css">


<div>
  <h3>Download</h3>
  <a href="<?php echo $this->webroot?>/journal/view/?revisionId=<?php echo $this->resource->getRevision()->getKey()?>">Back to article</a>
  <br/>
  <br/>
  <ul>
    <?php
    $size = 0;
    $bitstreams = $this->resource->getRevision()->getBitstreams();
    foreach ($bitstreams as $bitstream)
      {
      $size += $bitstream->getSizebytes();
      }
    ?>
    <li><a href="<?php echo $this->webroot ?>/download?items=<?php echo $this->resource->getKey() ?>, <?php echo $this->resource->getRevision()->getRevision() ?>">Download All</a>
      (<?php echo MidasLoader::loadComponent("Utility")->formatSize($size); ?>)</li>
    <?php
    if($this->paper)
      {
      ?>
    <li><a href="<?php echo $this->webroot ?>/download?bitstream=<?php echo $this->paper->getKey() ?>">Download Paper</a>
    </li>
    <?php
      }
      ?>
  </ul>
</div>

<?php
  $disclaimerIndex = MidasLoader::loadModel("Setting")->getValueByName('licenseDisclaimer', "journal");
  $disclaimer = MidasLoader::loadModel("Disclaimer", "journal")->load($disclaimerIndex);
  if($disclaimer)
    {
    echo '<div id="disclaimerWrapperLicense" style="display:none;width:700px;"><h4>Disclaimer</h4>';
    echo "<pre style:'white-space:pre-wrap'>".$disclaimer->getDescription()."</pre>";
    echo "<br>
      <table style='width:140px;margin:auto;'>
        <tbody><tr>
           <td> <a href='#' onclick='$.fancybox.close();'>Acknowledged</a></td>
              <td>|</td>
               <td><div align='center'><a href='".$this->webroot."/journal/view/?revisionId=".$this->resource->getRevision()->getKey()."'>Back</a></div></td>
          </tr>
        </tbody></table>";
    echo "</div>";
    }

if($this->resource->getDisclaimer() != -1)
  {
  $disclaimer = MidasLoader::loadModel("Disclaimer", "journal")->load($this->resource->getDisclaimer());
  if($disclaimer)
    {
    echo '<div id="disclaimerWrapper" style="display:none;width:700px;"><h4>Disclaimer</h4>';
    echo "<pre>".$disclaimer->getDescription().'</pre>';
    echo "<br>
      <table style='width:140px;margin:auto;'>
        <tbody><tr>
           <td> <a href='#' onclick='$.fancybox.close();'>Agree</a></td>
              <td>|</td>
               <td><div align='center'><a href='".$this->webroot."/journal/view/?revisionId=".$this->resource->getRevision()->getKey()."'>Decline</a></div></td>
          </tr>
        </tbody></table>";
    echo "</div>";
    }
  }
