<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/jquery-share/jquery.share.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/fancyapp/source/jquery.fancybox.pack.js');
$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/view/view.index.js');

$cssArray = Zend_Registry::get('notifier')->callback('CALLBACK_CORE_ITEM_VIEW_CSS', array('item' => $this->resource));
$jsArray = Zend_Registry::get('notifier')->callback('CALLBACK_CORE_ITEM_VIEW_JS', array('item' => $this->resource));

foreach ($jsArray as $module => $list)
  {
  foreach ($list as $script)
    {
    $this->headScript()->appendFile($script);
    }
  }
foreach ($cssArray as $module => $list)
  {
  foreach ($list as $stylesheet)
    {
    echo '<link type="text/css" rel="stylesheet" href="' . $stylesheet . '" />';
    }
  }
?>
<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/journal/public/css/view/view.index.css" rel="stylesheet" />
<link type="text/css" href="<?php echo $this->webroot ?>/privateModules/journal/public/js/lib/jquery-share/jquery.share.css" rel="stylesheet" />
<LINK rel="stylesheet" type="text/css" href="<?php echo $this->webroot ?>/privateModules/journal/public/js/lib/fancyapp/source/jquery.fancybox.css">
<div class="ContentWithRightPanel">
  <div class="Panel">

    <h4>Resources</h4>
    <ul>
      <li><a href="<?php echo $this->webroot ?>/download?items=<?php echo $this->resource->getKey() ?>, <?php echo $this->resource->getRevision()->getRevision() ?>">Download</a> 
        (<?php echo MidasLoader::loadComponent("Utility")->formatSize($this->resource->getSizebytes()); ?>)</li>
      <?php
      $github = $this->resource->getGithub();
      if(!empty($github))
        {
        ?>
        <li><a href="<?php echo $github ?>" target="_blank">
             Github <img  style='border:none;position:relative;top:-2px;' src="<?php echo $this->webroot ?>/privateModules/journal/public/images/github-small.png" /></a> 
        </li>
      <?php
        }
      ?>
    </ul>


    <h4>Export citation:</h4> 
    <ul><li>
    <form action="" method="post" name="form1" id="form1">
     <select name="exportType">
      <option value="bibtex">Bibtex</option>
      <option value="xml">XML</option>
      </select>
      <input type="submit"  value="Export"/>
    </form>
    </li></ul>

    <h4>Statistics</h4> 
    <ul>
      <li>Views: <?php echo $this->resource->getView() ?></li>
      <li>Downloads: <?php echo $this->resource->getDownload() ?></li>
    </ul>
    <?php
    echo '<div id="ratingContainer">';
   // echo $this->element("rating", "ratings");
    echo '</div>';
    ?>

    <h4>Information</h4> 
    <ul>
       <?php
      if($this->isPrivate)
        {
        echo "<li>Private article</li>";
        }
        ?>
      <?php
      $articleType = array(RESOURCE_TYPE_SOFTWARE => "Software",
         RESOURCE_TYPE_PLUGIN => "Plugin",
         RESOURCE_TYPE_PUBLICATION => "Publication",
         RESOURCE_TYPE_TUTORIAL => "Tutorial",
         RESOURCE_TYPE_DATASET => "Dataset");?>
      
      <?php
      $level = $this->resource->getCertificationLevel();
      if(is_numeric($level))
        {
        echo "<li><b>Certified</b> (level ".$level.")</li>";
        }
      ?>
       
      <li>Type: <?php echo $articleType[$this->resource->getType()] ?></li>
      <li>Categories: <?php 
      $categories = $this->resource->getCategories();
      foreach($categories as &$category)   
        {
        $tmpCat = MidasLoader::loadModel('Category', 'journal')->load($category);
        if($tmpCat) $category = '<a href="'.$this->webroot.'/journal/?category='.$tmpCat->getKey().'">'.$tmpCat->getName().'</a>';
        }
      echo join(', ', $categories) ?></li>
      <li>Keywords: <?php
      $tags = $this->resource->getTags();
      foreach($tags as &$tag)   $tag = '<a href="'.$this->webroot.'/journal/?q=text-journal.tags:'.$tag.'">'.$tag.'</a>';
      echo join(', ', $tags)
      ?></li>
      <?php
      $grant = $this->resource->getGrant();
      if(!empty($grant))
        {
        ?>
        <li>Grand: <?php echo $grant ?></li>
      <?php
        }
      $lastRevision = MidasLoader::loadModel('Item')->getLastRevision($this->resource);
      if($lastRevision->getRevision() != 1)
        {
        echo "<li>Current revision: <select id='revisionSelector'>";
        $currentRevision = $this->resource->getRevision()->getRevision();
        for($i = $lastRevision->getRevision(); $i > 0; $i--)
          {
          $revision = MidasLoader::loadModel("Item")->getRevision($this->resource, $i);
          if($revision)
            {
            echo "<option value='".$revision->getKey()."'";
            if($currentRevision == $i) echo "selected ";
            echo ">".$i."</option>";
            }
          }
        echo "</select></li>";
        }
      $sourceLicense = $this->resource->getSourceLicense();
      if(!empty($sourceLicense) && $sourceLicense > "0")
        {
        echo "<li>License: <a href='http://www.apache.org/licenses/LICENSE-2.0.html'>Apache 2</a></li>";
        }
      ?>
      <?php if ($this->resource->getPrivacyStatus() == MIDAS_PRIVACY_PRIVATE) echo '<li>This publication is private.</li>'; ?>
    </ul>
    <h4>Share</h4> 
    <ul style="list-style: none;"><li>
    <div id="shareDiv"></div>
    </li></ul>
    
    <?php
    if($this->isAdmin || $this->isAuthor)
      {
      echo '<h4>Manage</h4>';
      echo "<ul>";
      if($this->isAdmin || $this->isAuthor)
        {
        echo "<li><a href='" . $this->webroot . "/journal/submit?itemId=" . $this->resource->getKey() . "'>New revision</a></li>";
        }
      if($this->isAdmin)
        {
        echo "<li><a href='" . $this->webroot . "/journal/submit?revisionId=" . $this->resource->getRevision()->getKey() . "'>Edit resource</a></li>";
        echo "<li><a  onclick=\"return confirm('Do you want to delete the resource?');\" href='" . $this->webroot . "/journal/submit/delete?itemId=" . $this->resource->getKey() . "'>Delete resource</a></li>";
        if($this->resource->getRevision()->getRevision() > 1) echo "<li><a onclick=\"return confirm('Do you want to delete the revision?');\" href='" . $this->webroot . "/journal/submit/delete?revisionId=" . $this->resource->getRevision()->getKey() . "'>Delete current revision</a></li>";
        }
      $elements = Zend_Registry::get('notifier')->callback('CALLBACK_JOURNAL_MANAGE', array('resource' => $this->resource, 'isAdmin' => $this->isAdmin));
      echo join(' ', $elements);
      echo "</ul>";
      }
      ?>
  </div>
  
  
  
  <div class="MainContent">
    <div id="publication">
      <br/>
      <div class="title" >
        <?php echo $this->resource->getName() ?>       
      </div>
      <div class="authors"><?php 
      $authors = $this->resource->getAuthors();
      foreach($authors as &$author) $author = '<a href="'.$this->webroot.'/journal/?q=text-journal.authors:'.$author[0].' '.$author[1].'">'.ucfirst($author[1]).' '.ucfirst($author[0][0]).'.</a>';
      echo join(', ', $authors);
      ?></div>
      <div class="institution" > <a href="<?php echo $this->webroot ?>/journal/?q=text-journal.insitution:<?php echo ucfirst($this->resource->getInstitution()) ?>">
          <?php echo ucfirst($this->resource->getInstitution()) ?></a></div>
      <center>
        <?php
        if($this->resource->getLogo())
          {
          echo '<br/><img class="ResultLogo" src="'.$this->webroot.'/journal/view/logo/?revisionId='.$this->resource->getRevision()->getKey().'&size=300" /><br/><br/>';
          }
        $handleUrl = "http://hdl.handle.net/".$this->resource->getHandle();
        ?>
        
        <span style="background-color: #F2F3F3;">Please use this identifier to cite or link to this publication: <a href="<?php echo $handleUrl?>"><?php echo $handleUrl?></a></span><br/>
        <?php
        if(!$this->isApproved)
          {
          echo "<span style='font-weight:bold;color:red;'>This article is waiting for approval</span>";
          }
          ?>
      </center>

      <div class="journal">
        Published in <a href="<?php echo $this->webroot ?>/journal?community=<?php echo $this->community->getKey() ?>"
                        ><?php echo $this->community->getName(); ?></a> - <a 
                        href="<?php echo $this->webroot ?>/journal?issue=<?php echo $this->issue->getKey() ?>"><?php echo $this->issue->getName() ?></a>.

      </div>
      <div class="submittedby">Submitted by <?php echo $this->resource->getRevision()->getUser()->getFullName() ?> on <?php echo date("m-d-Y", strtotime($this->resource->getRevision()->getDate())) ?>.</div>
      <div class="abstract" style="text-align: justify;"><?php echo str_replace("<br>", "<br/>", nl2br($this->resource->getDescription())) ?></div>
    </div> <!-- End publication -->
    
    <?
    $elements = Zend_Registry::get('notifier')->callback('CALLBACK_JOURNAL_REVIEW', array('resource' => $this->resource, 'isAdmin' => $this->isAdmin));
    $element = end($elements);   
    if(is_array($element))
      {
      echo $this->action($element['action'], $element['controller'], $element['module'], $element['params']);
      }?>
    <h4>Comments</h4>
    <?php
    echo '<div id="commentsContainer" >';
    echo $this->element("comment", "comments");
    echo '</div>';
    ?>    
  </div>  
</div>


<?php
if($this->resource->getDisclaimer() != -1)
  {
  $disclaimer = MidasLoader::loadModel("Disclaimer", "journal")->load($this->resource->getDisclaimer());
  if($disclaimer)
    {
    echo '<div id="disclaimerWrapper" style="display:none;width:700px;"><h4>Disclaimer</h4>';
    echo "<pre>".$disclaimer->getDescription().'</pre>';
    echo "<br>
      <table style='width:140px;margin:auto;'>
        <tbody><tr>
           <td> <a href='#' onclick='$.fancybox.close();'>Agree</a></td>
              <td>|</td>
               <td><div align='center'><a href='".$this->webroot."/journal'>Decline</a></div></td>
            
          </tr>
        </tbody></table>";
    echo "</div>";
    }  
  }
