<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>

<div >   
  <br/>
  <div align="center">
    <font size="+1"><strong>Journals</strong>
    </font>
  </div>
  <br/>   

  <?php
  foreach($this->communities as $community)
    {
    echo "<h3 style='margin-bottom:3px'><a href='".$this->webroot."/journal?community=".$community->getKey()."'>".$community->getName()."</A></h3>";
    echo "<div>".nl2br($community->getDescription())."</div>";
    }
    ?>
</div>
