<?php
/*=========================================================================
 *
 *  Copyright OSHERA Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/
?>
<style type="text/css">
  <!--
  .style1 {color: #FF0000}
  -->
</style>

<?php 

$this->headScript()->appendFile($this->webroot . '/privateModules/journal/public/js/lib/parsley.min.js');
?>

<br/>
<div align="center"><font size="+1"><strong>Send a feedback</strong></font></div>
<?php echo @$this->error ?>
<br/>
<?php
if (empty($this->sent))
  {
  ?>
  <form action="" method="post" name="form1" id="form1" data-validate="parsley">
    <table width="70%"  border="0">
      <tr><td>
          <input type="hidden" name="timer"/>
          <div class="required-fields">
            <intput type="name" />
            <intput type="mail" />
            <intput type="age" />
            <intput type="timer"  value="<?php echo $this->time?>"/>
          </div>
          <?php
          $type = '';
          if ($this->logged)
            {
            $type = " type=\"hidden\" ";
            }
          else
            {
            ?>
          </td></tr>
        <tr><td>
            <div class="submission">
              <div class="title"><span class="style1">* </span>Your e-mail address</div>
              <div class="caption"></div>
            </div>
          </td></tr>
        <tr><td>
          <?php }
          ?>
          <input name="email" <?php echo $type ?> class="textbox" id="Title" size="65" data-type="email" data-required="true" value="<?php echo $this->forms['email'] ?>"/>
        </td></tr>
      <tr><td>
          <div class="submission">
            <div class="title">Location of the problem </div><div class="caption">Give us an internet address (url) if possible</div>
          </div>
        </td></tr>
      <tr><td>
          <input name="where" class="textbox" id="Title" size="65" value="<?php echo $this->forms['where'] ?>"/>
        </td></tr>
      <tr><td>
          <div class="submission">
            <div class="title"><span class="style1">* </span>What is the problem?</div>
            <div class="caption">Please be as specific as possible in your report</div>
          </div>
        </td></tr>
      <tr><td>
          <textarea name="what" cols="65" rows="15" data-required="true" id="Summary" ><?php echo $this->forms['what'] ?></textarea>
        </td></tr>
      <tr><td>
          <div align="right">
            <input name="submit" type="submit" id="submit" value="Send feedback >>" />
          </div>
        </td></tr>
    </table>
  </form>

  <?php
  }
?>


